server:
  port: 8060

eureka:
  instance:
    hostname: localhost
    port: 8061
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
      - id: customer-service
        uri: lb://customer-service
        predicates:
        - Path=/gateway/**
        filters:
        - RewritePath=/customer/(?<path>.*),/$\{path}